#!/usr/bin/env python3
"""Generate site/intro-points.js — the point cloud the loading intro draws.

The intro does not ship stock footage. It draws the world out of the report's
own evidence: every marker on site/map.html, projected equirectangular and
quantised to a 1024x512 grid so the whole set costs a few kilobytes instead of
a video file. The silhouette that appears is therefore not a picture of the
world, it is the report's coverage of it, which is the only honest "clip from
the world" this site can claim to own.

Re-run after any change to the locations array:

    python3 scripts/build-intro-points.py

The parser is build-kml.py's, reused rather than rewritten, because the
locations literal is not JSON (// comments containing apostrophes, bare keys,
escaped quotes inside double-quoted strings) and must be walked, not regexed.
"""
import importlib.util
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, 'site', 'map.html')
OUT = os.path.join(ROOT, 'site', 'intro-points.js')

spec = importlib.util.spec_from_file_location(
    'build_kml', os.path.join(ROOT, 'scripts', 'build-kml.py'))
bk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bk)


def main():
    text = open(MAP, encoding='utf-8').read()
    locations = bk.js_to_json(bk.extract_block(text, 'var locations = ['))

    seen, pts = set(), []
    for loc in locations:
        try:
            lat = float(loc['lat']); lng = float(loc['lng'])
        except (KeyError, TypeError, ValueError):
            continue
        if not (-90 <= lat <= 90 and -180 <= lng <= 180):
            continue
        x = int(round((lng + 180.0) / 360.0 * 1023))
        y = int(round((90.0 - lat) / 180.0 * 511))
        key = (x, y)
        # Co-located markers land on the same pixel at this resolution; one
        # dot is one place on screen, so the duplicates are dropped here
        # rather than drawn on top of each other.
        if key in seen:
            continue
        seen.add(key)
        pts.append([x, y])

    # Draw order is the reading order of the animation. Sorting west to east
    # makes the world assemble as a sweep instead of a scatter.
    pts.sort(key=lambda p: (p[0], p[1]))

    body = ('/* generated by scripts/build-intro-points.py - do not edit */\n'
            'window.B0B_INTRO_POINTS=%s;\n'
            'window.B0B_INTRO_TOTAL=%d;\n'
            % (json.dumps(pts, separators=(',', ':')), len(locations)))
    open(OUT, 'w', encoding='utf-8').write(body)
    print('wrote %s: %d distinct points from %d markers (%d bytes)'
          % (os.path.relpath(OUT, ROOT), len(pts), len(locations), len(body)))


if __name__ == '__main__':
    main()
