#!/usr/bin/env python3
"""Build site/listen-places.js - the gazetteer the listen-mode slideshow uses to
pin places the narrator is reading about.

Every entry comes from the map's own markers (site/map.html `locations`), so a
pin in the slideshow is a place the report already plots, with the same
section. Match keys are the marker name's leading phrase ("Headington Hill
Hall" from "Headington Hill Hall, Oxford (Pergamon Press HQ)") and the same
phrase with a generic tail word dropped ("Mount of Olives" from "Mount of Olives
Cemetery").

Excluded on purpose: the 161 mass-shooting markers. Their names identify
perpetrators, which is an open editorial question for the author (CLAUDE.md
section 7), and a slideshow should not surface them while that is unresolved.

    python3 scripts/build-listen-places.py
"""
import importlib.util
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'site', 'listen-places.js')

spec = importlib.util.spec_from_file_location('bk', os.path.join(ROOT, 'scripts', 'build-kml.py'))
bk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bk)

GENERIC = r'\s+(Cemetery|Headquarters|HQ|Complex|Center|Centre|Facility|Campus|Building|Site|Base|Station|Office|Offices|Plant)$'
TOO_BROAD = {'United States', 'New York', 'Washington', 'London', 'Paris', 'China', 'Russia', 'Israel', 'Iran',
             'Europe', 'Africa', 'Asia', 'Moscow', 'Beijing', 'California', 'Florida', 'Texas', 'Virginia'}


def keys_for(name):
    lead = re.split(r'\s+-\s+|\s+\(|,\s+|\s+/\s+', name, maxsplit=1)[0].strip()
    out = []
    for k in (lead, re.sub(GENERIC, '', lead)):
        k = k.strip(' .')
        if len(k) >= 5 and k[0].isupper() and k not in TOO_BROAD and k not in out:
            out.append(k)
    return out


def main():
    text = open(bk.SRC, encoding='utf-8').read()
    locs = bk.js_to_json(bk.extract_block(text, 'var locations = ['))
    rows, seen = [], set()
    for loc in locs:
        if loc.get('type') == 'mass-shooting':
            continue
        try:
            lat, lng = float(loc['lat']), float(loc['lng'])
        except (KeyError, TypeError, ValueError):
            continue
        x = int(round((lng + 180.0) / 360.0 * 1023))
        y = int(round((90.0 - lat) / 180.0 * 511))
        for k in keys_for(loc['name']):
            if k in seen:
                continue
            seen.add(k)
            rows.append([k, x, y, loc.get('section', ''), loc.get('type', ''), loc['name']])
    rows.sort(key=lambda r: -len(r[0]))   # longest key first, so the most specific match wins
    js = ('/* generated by scripts/build-listen-places.py from site/map.html - do not edit */\n'
          'window.B0B_LISTEN_PLACES=%s;\n' % json.dumps(rows, ensure_ascii=False, separators=(',', ':')))
    open(OUT, 'w', encoding='utf-8').write(js)
    print('wrote %s: %d keys from %d markers (%.1f KB)' % (os.path.relpath(OUT, ROOT), len(rows), len(locs), len(js) / 1024))


if __name__ == '__main__':
    main()
